//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tikee.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tikee.Resources.Errors.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigDirectoryCreation_Generic {
            get {
                return ResourceManager.GetString("ConfigDirectoryCreation_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigDirectoryCreation_NotSupportedException {
            get {
                return ResourceManager.GetString("ConfigDirectoryCreation_NotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigDirectoryCreation_PathTooLongException {
            get {
                return ResourceManager.GetString("ConfigDirectoryCreation_PathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigDirectoryCreation_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("ConfigDirectoryCreation_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigFileGeneration_DirectoryNotFoundException {
            get {
                return ResourceManager.GetString("ConfigFileGeneration_DirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigFileGeneration_Generic {
            get {
                return ResourceManager.GetString("ConfigFileGeneration_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigFileGeneration_IOException {
            get {
                return ResourceManager.GetString("ConfigFileGeneration_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigFileGeneration_SecurityException {
            get {
                return ResourceManager.GetString("ConfigFileGeneration_SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error blah blah.
        /// </summary>
        internal static string ConfigFileGeneration_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("ConfigFileGeneration_UnauthorizedAccessException", resourceCulture);
            }
        }
    }
}
